### ISSUE TITLE
Fails on first run as per latest documentation

### ISSUE THREAD

**Issue by robross0606** [nodesource/docker-nsolid#62]
Fails to run using `docker compose` as per latest documentation:
```
2024-09-06 16:40:59 {"level":30,"time":1725655259858,"pid":7,"hostname":"6af27662af4d","name":"nsolid-console","name":"nsolid-console:nsolid-console.js","msg":"N|Solid Console Service starting up with PID 7 (id: fc784f05927c77001542b566016fc00028c92ede)"}
2024-09-06 16:41:01 {"level":30,"time":1725655260973,"pid":7,"hostname":"6af27662af4d","name":"nsolid-console","name":"nsolid-console:lib/settings-manager.js","msg":"using LevelDB"}
2024-09-06 16:41:01 {"level":30,"time":1725655261008,"pid":7,"hostname":"6af27662af4d","name":"nsolid-console","name":"nsolid-console:lib/settings-manager.js","msg":"Beginning cleanup of old agent data"}
2024-09-06 16:41:01 {"level":50,"time":1725655261170,"pid":7,"hostname":"6af27662af4d","name":"nsolid-console","name":"nsolid-console:nsolid-console.js","msg":"stopping process; reason: uncaughtException"}
2024-09-06 16:41:01 {"level":50,"time":1725655261170,"pid":7,"hostname":"6af27662af4d","name":"nsolid-console","name":"nsolid-console:nsolid-console.js","err":{"type":"Error","message":"Error accessing settings database, is another instance of nsolid-console running?  LevelDB error: OpenError","stack":"Error: Error accessing settings database, is another instance of nsolid-console running?  LevelDB error: OpenError\n    at Immediate.<anonymous> (/usr/src/app/lib/connector-leveldb.js:64:15)\n    at process.processImmediate (node:internal/timers:478:21)"},"msg":"Error accessing settings database, is another instance of nsolid-console running?  LevelDB error: OpenError"}
2024-09-06 16:41:01 {"level":50,"time":1725655261170,"pid":7,"hostname":"6af27662af4d","name":"nsolid-console","name":"nsolid-console:nsolid-console.js","msg":"InfluxDB did not successfully start; exiting"}
2024-09-06 16:45:57 {"level":50,"time":1725655557059,"pid":7,"hostname":"6af27662af4d","name":"nsolid-console","name":"nsolid-console:lib/util.js","err":{"type":"Error","message":"EACCES: permission denied, mkdir '/var/lib/nsolid/console/data'","stack":"Error: EACCES: permission denied, mkdir '/var/lib/nsolid/console/data'\n    at Object.mkdirSync (node:fs:1398:3)\n    at Object.ensureDirExists (/usr/src/app/lib/util.js:129:8)\n    at getConfig (/usr/src/app/lib/config.js:134:12)\n    at new WorkerPool (/usr/src/app/lib/worker-pool.js:17:21)\n    at Object.<anonymous> (/usr/src/app/lib/worker-pool.js:149:18)\n    at Module._compile (node:internal/modules/cjs/loader:1278:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1332:10)\n    at Module.load (node:internal/modules/cjs/loader:1141:32)\n    at Module._load (node:internal/modules/cjs/loader:982:12)\n    at Module.require (node:internal/modules/cjs/loader:1165:19)","errno":-13,"syscall":"mkdir","code":"EACCES","path":"/var/lib/nsolid/console/data"},"msg":"error creating directory: /var/lib/nsolid/console/data"}
2024-09-06 16:45:57 /usr/src/app/lib/worker-pool.js:18
2024-09-06 16:45:57       this.config.assets = this.config.assets || { summaryTimeout: 0, summaryLimit: 'true' }
2024-09-06 16:45:57                                        ^
2024-09-06 16:45:57 
2024-09-06 16:45:57 TypeError: Cannot read properties of null (reading 'assets')
2024-09-06 16:45:57     at new WorkerPool (/usr/src/app/lib/worker-pool.js:18:40)
2024-09-06 16:45:57     at Object.<anonymous> (/usr/src/app/lib/worker-pool.js:149:18)
2024-09-06 16:45:57     at Module._compile (node:internal/modules/cjs/loader:1278:14)
2024-09-06 16:45:57     at Module._extensions..js (node:internal/modules/cjs/loader:1332:10)
2024-09-06 16:45:57     at Module.load (node:internal/modules/cjs/loader:1141:32)
2024-09-06 16:45:57     at Module._load (node:internal/modules/cjs/loader:982:12)
2024-09-06 16:45:57     at Module.require (node:internal/modules/cjs/loader:1165:19)
2024-09-06 16:45:57     at require (node:internal/modules/cjs/helpers:119:18)
2024-09-06 16:45:57     at Object.<anonymous> (/usr/src/app/lib/nsolid-console.js:16:23)
2024-09-06 16:45:57     at Module._compile (node:internal/modules/cjs/loader:1278:14)
2024-09-06 16:45:57 
2024-09-06 16:45:57 Node.js v18.18.2
```

**Comment by robross0606** [comment]
I think this is because the image does `user nsolid` but there is no indication in the documentation as to which user that is or what it maps to in terms of UID.
